namespace Banking.Core.Entities;

public class Account
{
    public int Id { get; private set; }
    public int CustomerId { get; private set; }
    public decimal Balance { get; private set; }
    public AccountType AccountType { get; private set; }
    public bool IsClosed { get; private set; }

    // For a real app, this would most likely be private, a factory would be used, 
    // and id would be generated by the database or a service.
    public Account(int id, int customerId, decimal balance, AccountType accountType)
    {
        Id = id; 
        CustomerId = customerId;
        Balance = balance;
        AccountType = accountType;
        IsClosed = false;
    }

    public static Account CreateNew(int customerId, decimal amount, AccountType accountType, bool isFirst)
    {
        if (isFirst && accountType != AccountType.Savings)
            throw new ArgumentException("First account must be a Savings account.");

        if (amount < 100)
            throw new ArgumentException("Initial deposit must be at least 100.");

        return new Account(0, customerId, amount, accountType);
    }

    public void Deposit(decimal amount)
    {
        if (amount <= 0)
            throw new ArgumentException("Deposit amount must be positive.");

        Balance += amount;
    }

    public void Withdrawal(decimal amount)
    {
        if (amount <= 0)
            throw new ArgumentException("Withdrawal amount must be positive.");

        if (amount > Balance)
            throw new ArgumentException("Insufficient funds.");

        Balance -= amount;
    }

    public void Close()
    {
        if (IsClosed)
            throw new InvalidOperationException("Account is already closed.");

        if (Balance != 0)
            throw new InvalidOperationException("Account balance must be zero to close.");

        IsClosed = true;
    }
}